---
title: "Zambia nightlights data analysis"
output: html_notebook
---

```{r packages, message=FALSE}
library(tidyverse)
```



I used the cluster center coordinates recorded in 2015 (not 2012).

### Creating forest loss table
``` {r forest lost}
#### TRY WITH jsonlite PACKAGE ####
buffered_lossyear <- jsonlite::fromJSON('Data/buffered_lossyear.geojson') 

#cluster id array
cluster <- rep(buffered_lossyear$features$properties$cluster, each = 7)
forestloss <- tibble(cluster)

#Brining list of dataframes to just one table.
hist_results <- plyr::ldply(buffered_lossyear$features$properties$histogram, rbind)
colnames(hist_results) <- c('year', 'count')

#is any list null?
lapply(buffered_lossyear$features$properties$histogram, is.null)

#combing cluster id array and reulst
forestloss <- forestloss %>% 
  cbind(hist_results) %>% 
  mutate(year = (year + 2000) %>% as.integer())

head(forestloss)
```

### Creating nightlights time-series table
``` {r nightlights}
#### TRY WITH jsonlite PACKAGE ####
triplets <- jsonlite::fromJSON('Data/triplets.geojson') 

night <- as_tibble(triplets$features$properties) %>% 
  mutate(year = substr(imageId, start=1, stop = 4) %>% as.integer())
night
```

``` {r join}
#### TRY WITH jsonlite PACKAGE ####
clusters <- full_join(forestloss, night, by = c('cluster', 'year'))
head(clusters)
```
